apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-helloworld
    tag: latest
  name: python-helloworld
  namespace: app
spec:
  ports:
  - port: 6111
    protocol: TCP
    targetPort: 6111
    nodePort: 30009
  selector:
    app: python-helloworld
    tag: latest
  type: NodePort
